### PR TITLE
Show issue reviewers

### PR DESCRIPTION
**Pull request by kumar303**
Show all reviewers who approved the PR for each issue.

### CODE REVIEW

**Comment by muffinresearch** [comment]
@kumar303 one way I found to do this in the single query was via `CrossReferencedEvents` like so:

```graphql
timelineItems(first: 20, itemTypes: CROSS_REFERENCED_EVENT) {
  edges {
    event: node {
      ... on CrossReferencedEvent {
        source {
          ... on PullRequest {
            reviews(first: 10, states: APPROVED) {
              totalCount
              edges {
                review: node {
                  author {
                    login
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
```
Which provides something like this under the `results` array:

```json
"timelineItems": {
  "edges": [
    {
      "event": {
        "source": {}
      }
    },
    {
      "event": {
        "source": {
          "reviews": {
            "totalCount": 1,
            "edges": [
              {
                "review": {
                  "author": {
                    "login": "kumar303"
                  }
                }
              }
            ]
          }
        }
      }
    }
  ]
}
```

Which shows that complex relations are possible to traverse, however you might want to check this makes sense by testing this a bit more. E.g presumably you could have multiple reviewers and you're really need a way to see that that particular PR with that review resulted in closing this particular issue, but it's a start.

**Comment by kumar303** [comment]
@muffinresearch hey, cool, I kinda got it working. It only shows approved reviewers now. The one limitation is that it will show any approved review from PRs that simply *mention* the issue. Really, it should show only those that use the magic "fixes" prefix.

I thought maybe I could do this by looking at [`willCloseTarget`](https://developer.github.com/v4/object/crossreferencedevent/#fields) in `CrossReferencedEvent` but that seems to always be `false`.

Here is one example: http://localhost:3000/milestones/2019.08.15/?dir=asc&sort=assignee . Issue `#11780` will show approvals from both https://github.com/mozilla/addons-server/pull/11988 and https://github.com/mozilla/addons-server/pull/12068 but that first PR should be ignored.

It's probably good enough, though!

Is there a better way to generate the milestone data test fixture?

**Comment by muffinresearch** [comment]
Looks good. Should the reviewers list be de-duped? I currently see a few examples with the same reviewer a few times:

See http://localhost:3000/milestones/2019.09.12/?dir=asc&sort=assignee

Milestones_-_Add-ons_PM

Milestones_-_Add-ons_PM

Would be nice to ensure 3 reviewers can fit in the cell before wrapping if possible as that should help reduce the page length.

**Comment by muffinresearch** [comment]
Would it be possible to add some assertions that the reviewers content is rendered?

**Comment by kumar303** [comment]
I didn't see an obvious way to do it initially but I'll take a second look at the tests.

**Comment by kumar303** [comment]
This should definitely de-dupe the icons. I actually had that in there originally but deleted it for some reason!

**Comment by muffinresearch** [comment]
> I didn't see an obvious way to do it initially but I'll take a second look at the tests.

Yeah tests are quite minimal at the moment. There's definitely room for improvement.

**Comment by muffinresearch** [comment]
I'm going to land this and add the de-duping functionality so it can be deployed.

**Pull request merged**
